#!/bin/sh
kextunload -b net.sf.tuntaposx.tap || true
kextunload -b net.sf.tuntaposx.tun || true
kill -2 $(ps aux | grep Pritunl.app | awk '{print $2}') || true
launchctl unload /Library/LaunchDaemons/com.pritunl.service.plist || true
