#!/bin/sh
kill -2 $(ps aux | grep Pritunl.app | awk '{print $2}') || true
launchctl unload /Library/LaunchAgents/com.pritunl.client.plist || true
launchctl unload /Library/LaunchDaemons/com.pritunl.service.plist || true
